- _policies/canada.md
- _policies/china.md
- _policies/european union.md
adding Canada, China, and European Union
> adding first round of updates to policies content

- _policies/united states.md
Added some of the U.S. policies to test.
> Maryjom add policies us india israel

- _help/1-disclaimer.md
- _includes/footer.html
- index.html
Added collapsible container for disclaimer, edited content with shorter
version, and added link in footer to disclaimer.
Addresses GitHub issue #1
> Disclaimer edits

- index.html
> added summary to disclaimer

- index.html
> adding div to details for content

- _help/2-status.md
- _help/2-updates.md
Removed status language and added button to this section - addresses issue #12
> De-wording status and updates

- _data/standards.yaml
- _policies/united states.md
Update U.S. laws to fix bugs and add the rest of the laws and references.
> Maryjom update us policies

- index.html
> clarifying left nav links for table and detail sections

- index.html
> add pseudo filters for group discussion

- _policies/australia.md
- index.html
Multiple updates for verbiage - MaryJo and Robert working session
> Robert maryjo verbiage 01

- _policies/australia.md
- _policies/canada.md
- _policies/china.md
- _policies/european union.md
- _policies/france.md
- _policies/germany.md
- _policies/united states.md
- index.html
Addresses issues #43, #21, and #6
> Change from 'status' to 'enactdate' for table and country details.

- _policies/germany.md
> Update Germany information

- _policies/australia.md
- _policies/united states.md
Fixed some verbiage consistency issues in United States and Australia information.  Also added the CVAA law to the U.S. information.
> Maryjom update U.S. & Australia

- _policies/australia.md
- _policies/canada.md
Updated Canada and Australia to make verbiage used more consistently.
> Making verbiage consistent

- _help/4-terms.md
Changes needed to address Issues #2, #3 and #4.
> Maryjom update definitions based on comments received.

- _layouts/page.html
> added WCAG Version Used to policies detail page

- _help/1-introduction.md
- index.html
> moved terms to bottom of page

- index.html
Resolves issue #46 by adding visually-hidden policy title to link text
> added visually-hidden text

- _layouts/page.html
- _policies/united states.md
- index.html
> Add support for multiple standards

- _policies/denmark.md
Adding placeholders for other countries so we can see the table with more data.
> Add placeholder for Denmark

- _policies/finland.md
- _policies/hong_kong.md
- _policies/israel.md
- _policies/italy.md
- _policies/japan.md
Add placeholders for countries represented in the current Web policies page.
> Maryjom issue #56

- index.html
> and capitalize country names in table, too

- index.html
now is a td properly, resolves issue #70
> fix errant th causing boldness and likely other issues

- _layouts/page.html
Addresses issue #86 but only partially
> added simple breadcrumb nav for country detail pages

- _layouts/page.html
- index.html
Added nested list like Relevant Documents
Added logic to use singular or plural version for 1 or more standards,
respectively.
> Display enhancement for listing of standards for policies

- _layouts/page.html
- _policies/european union.md
- index.html
> Created left-side nav with country links on country detail page

- index.html
> Update to heading structure

- submission.html
Using different stylesheet, so this needed updating. Resolves issue #94
> Replace class 'visuallyhidden' with 'no-display'

- _help/1-introduction.md
Implemented @slhenry’s proposed edits to the introduction, addressing
issue #13.
Link to terms remains in place until filters are dealt with (separate
proposal may have us move the terms and this link).
Additions and corrections link to submission form may be redundant in
the introduction section.
> Revisions to Introduction

- js/data.json
solved problem of creating clean json with jekyll loops
> data.json loop conditional logic update

- index.html
- index.html.OLD
Resolves #56
Related to #19 and #124
> Remove countries from index, add filters to index

- index.html
- js/script.js
> Clear all filters button and functionality enabled

- _help/1-introduction.md
- _layouts/page.html
- index.html
- submission.html
> Moved terms to intro, IE styling fixes

- _data/standards.yaml
- _policies/australia.md
- _policies/european union.md
- _policies/india.md
Did several changes to make data more consistent, provide WCAG level in descriptions, and add in link to Australia state page.
> Maryjom update country info

- index.html
> Remove details/summary from table

- submission.html
> Removed email list reference from form

- index.html
- js/script.js
> Update filters and table headings for consistency

- js/script.js
> Specify sort order of filter facets under WCAG Version Used

- index.html
> Make Filters Collapsible Again

- _help/1-introduction.md
> Added definitions identified during usability test

- _policies/norway.md
Missing info:
Will eventually fix #253
> Add Norway

- _policies/european union.md
Relates to issue #261
Signed-off-by: Robert Jolly <jolly.robert@gmail.com>
> Updates to EU page

- _policies/republic-of-korea.md
> Republic of Korea

- _policies/germany.md
> Law -> Policy

- _policies/taiwan.md
> Add Taiwan

- _policies/sweden.md
Missing:
Eventually fixes #249
> Swedish policy

- _policies/taiwan.md
Thank you very much @marisatyyang!
> Add scope and Chinese title of policy

- _policies/sweden.md
Fix for #319
@maryjom does this address your comments in #319?
> Update for Sweden

- _policies/index.md
> Change for #351

- _policies/united-states.md
Reverts w3c/wai-policies-prototype#400
> Revert "delete US Section 504"

- _policies/submission.md
lots more clean up needed, though, e.g., checkbox alignment
> correct typos and wording; delete repetitive abbrs, and 1.0

- _policies/argentina.md
This is related to comment on https://github.com/w3c/wai-policies-prototype/pull/473#issuecomment-1425123891
> Test fix for missing official page link

- _policies/index.md
preview: https://deploy-preview-492--wai-policies-prototype.netlify.app/policies/
> February -> April

- _policies/canada.md
Bringing over issues from https://github.com/w3c/wai-policies-prototype/issues/384 & extending them a bit.
The Accessible Canada Act wasn't listed.
> [Canada] Including the ACA

- _policies/estonia.md
> Add policies to Estonia

- _policies/malta.md
Added "Accessibility of the Websites and Mobile Applications of Public Sector Bodies Regulations"
> Add policy to Malta

- _policies/romania.md
Added Emergency Ordinance No. 112/2018
> Add policy to Romania

- _policies/poland.md
Added "Act of 4 April 2019 on the digital accessibility..."
> Add policy to Poland

- _policies/austria.md
> Add policies to Austria

- _policies/latvia.md
Added "Procedure in which institutions post information on the Internet"
> Add policy to Latvia

- _policies/lithuania.md
Three new policies added
Preview: (hope this works?) https://deploy-preview-484--wai-policies-prototype.netlify.app/policies/lithuania
> Add policies to Lithuania

- _config.yml
- _layouts/policy.html
- _policies/index.md
Option can be over ridden using the Frontmatter on any page
> Add in disclaimer on all pages

- _policies/submission.md
[Direct link to preview](https://deploy-preview-558--wai-policies-prototype.netlify.app/policies/submission/#fs-guideline)
Resolves https://github.com/w3c/wai-policies-prototype/issues/555
> Add WCAG 2.2 in submission form
